const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

test('daemon tui rpc keeps daemon-owned session runtimes and restart recovery markers', () => {
  const source = fs.readFileSync(path.join(__dirname, '..', 'src', 'daemon-tui-rpc.ts'), 'utf8')

  assert.match(source, /reconnectGeneration/)
  assert.match(source, /restartResumePath/)
  assert.match(source, /consumeRestartResumeMarker/)
  assert.match(source, /const runtimes = new Map/)
  assert.match(source, /const socketToRuntime = new Map/)
  assert.match(source, /runtime:\$\{nodeCrypto\.randomUUID\(\)\}/)
  assert.doesNotMatch(source, /return 'local:default'/)
  assert.match(source, /eventBacklog/)
  assert.match(source, /lastEventSeq/)
  assert.match(source, /attachRuntimeForSocket/)
  assert.match(source, /replayRuntimeEventsToSocket/)
  assert.match(source, /session\.getSteeringMessages\?\.\(\)/)
  assert.match(source, /runtimeHasResumeWork/)
  assert.match(source, /autoResume: Boolean\(item && item\.autoResume\)/)
  assert.match(source, /rememberAutoResumeIntent/)
  assert.match(source, /autoResumeIntent = false/)
  assert.match(source, /clientInstanceIds: Array\.isArray\(item && item\.clientInstanceIds\)/)
  assert.match(source, /viewerBindingPath/)
  assert.match(source, /readViewerBindings/)
  assert.match(source, /setViewerBinding/)
  assert.match(source, /clearViewerBinding/)
  assert.match(source, /findRestartResumeMarker/)
  assert.match(source, /clientInstanceId = nodeCrypto\.randomUUID\(\)/)
  assert.match(source, /viewerBindings\.get\(clientInstanceId\)/)
  assert.match(source, /if \(clientInstanceId && \(reconnectGeneration > 0 \|\| hasExplicitTarget\)\) setViewerBinding\(clientInstanceId, nextRuntime\)/)
  assert.match(source, /else if \(clientInstanceId\) clearViewerBinding\(clientInstanceId\)/)
  assert.match(source, /const requestedAutoResume = Boolean\(targetPayload && targetPayload\.autoResume\)/)
  assert.match(source, /runtime\.restartRecoveryHandled = true/)
  assert.match(source, /if \(shouldAutoResume && !runtime\.restartRecoveryTurnTriggered\)/)
  assert.match(source, /buildTuiDaemonRestartSystemPromptExtra/)
  assert.match(source, /autoResume: shouldAutoResume/)
  assert.match(source, /if \(shouldAutoResume && !runtime\.restartRecoveryTurnTriggered\) \{/)
  assert.match(source, /void runtime\.session\.sendCustomMessage\(/)
  assert.match(source, /type: 'daemon_restart_recovery'/)
  assert.match(source, /resumed the interrupted turn automatically/)
  assert.match(source, /Reopened this TUI session from the last saved state\./)
})

test('vendored rin daemon mode treats queued input as daemon-owned remote state', () => {
  const source = fs.readFileSync(path.join(__dirname, '..', 'third_party', 'pi-mono', 'packages', 'coding-agent', 'dist', 'modes', 'interactive', 'rin-daemon-mode.js'), 'utf8')

  assert.match(source, /type === 'client_reconnecting'/)
  assert.match(source, /clearTransientRuntimeState\(\)/)
  assert.match(source, /emitInterruptedRuntimeEndEvents\(interrupted\)/)
  assert.match(source, /type === 'daemon_restart_recovery'/)
  assert.match(source, /Waiting for daemon/)
  assert.match(source, /this\.currentState && this\.currentState\.steeringMessages/)
  assert.match(source, /await this\.refreshRemote\(\)/)
  assert.doesNotMatch(source, /replayPendingQueueAfterReconnect\(\)/)
  assert.doesNotMatch(source, /this\.steeringMessages/)
  assert.doesNotMatch(source, /this\.followUpMessages/)
  assert.doesNotMatch(source, /emitDaemonRestartNotice\(noticeText\)/)
  assert.doesNotMatch(source, /customType: 'daemonRestart'/)
  assert.doesNotMatch(source, /resumed the interrupted turn automatically/)
})
